# action.yml
name: 'Polling Jit'
description: 'Poll Jit service until getting correct status'
inputs:
  retry:
    description: 'Number of retry attempts'
    required: false
    default: '10'
  retry-delay:
    description: 'Time to wait between requests'
    required: false
    default: '6'
  payload:
    description: 'Request payload'
    required: false
    default: ${{ github }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.retry }}
    - ${{ inputs.retry-delay }}
    - ${{ inputs.payload }}